### ISSUE TITLE
crawler for immowelt is grabbing to much

### ISSUE THREAD

**Issue by qudiqudi** [orangecoding/fredy#105]
**Describe the bug**
immowelt shows listings outside the filter criteria below the matched listings. Seperated by an info line:

<img width="1137" alt="Screenshot 2024-08-10 at 13 41 59" src="https://github.com/user-attachments/assets/75489016-a777-4c8b-ae11-a6457ade46a8">

Fredy, grabs these listings below that line as potential findings for the assigned job, which is incorrect. It's mostly outside the defined search radius.

Looks like it should stop at the alertBoxSeparator div class:

<img width="482" alt="Screenshot 2024-08-10 at 13 52 58" src="https://github.com/user-attachments/assets/e3a7add7-a648-4b96-a93d-7cf09c0e8200">

**Comment by orangecoding** [comment]
Immowelt is fucked up in general. Their source code is horribly broken at significant places. Whoever is maintains their websites, I often times thought their only purpose in life is giving me headaches ;)

**Comment by orangecoding** [comment]
Hey @qudiqudi my latest change should mitigate the issue. Plz check it out, but be aware of the breaking change (See Release Notes)

If it works, please close the issue

**Comment by qudiqudi** [comment]
Unfortunately, it still grabs listings below the divider.

<img width="1493" alt="Screenshot 2024-09-06 at 09 06 57" src="https://github.com/user-attachments/assets/54176f79-bb3c-4d09-a730-a7bec427cac3">

**Comment by orangecoding** [comment]
Im on vacation now. Will check afterwards. Maybe it has settled by then... ;)

**Comment by orangecoding** [comment]
Yeah. I'm currently busy with family related stuff. As soon as I can I will jump on it. But how about you give it a shot yourself and create a pr? ;)
