### ISSUE TITLE
Immowelt advertisements are not sent to Telegram

### ISSUE THREAD

**Issue by DerThermo** [orangecoding/fredy#109]
Is your feature request related to a problem? Please describe.
Since about two to three days, new listings from Immowelt are not being sent to the Telegram group. However, listings from eBay Kleinanzeigen and WG Gesucht are still being sent without any issues.

Describe the solution you'd like
I would like new listings from Immowelt to be sent to the Telegram group as they were before. The functionality for eBay Kleinanzeigen and WG Gesucht should remain unchanged.

Describe alternatives you've considered
I have checked the Telegram settings and confirmed that no changes have been made on my end. 

Additional context
This issue started approximately two to three days ago. It might be related to recent changes in how Emo-Welt listings are processed or delivered.

Thank you very much for your effort! We really appreciate it!

**Comment by dekiesel** [comment]
Just fyi: I just got a immowelt listing sent to my Telegram group (fredy 9.0.0)

**Comment by orangecoding** [comment]
Hey. Plz use the latest release, I fixed the issue. Be aware, this release has some breaking change. Listings that have been sent previously will most likely be sent again.

If it works, please close the issue

**Comment by DerThermo** [comment]
Thank you very much! It works totally fine!

**Comment by DerThermo** [comment]
Hi @orangecoding,

as mentioned in the discussion section (https://github.com/orangecoding/fredy/discussions/115#discussioncomment-1150686), just wanted to share information regarding this issue. Immowelt was actually working (for me) as of December 6th, but since then, it has stopped functioning again. Thank you so much in advance for looking into this!

Greetz!
DerThermo

**Comment by orangecoding** [comment]
@DerThermo Fixed here: https://github.com/orangecoding/fredy/commit/3c0e9e56c63a9ffdae223ee02a84093ba45a60ca

I'd really appreciate if you (or anybody reading this) would fix those small problems by yourself. This is why Fredy is Open Source. Fixing a provider (if they changed the selectors) is really not that hard after all ;)

**Comment by DerThermo** [comment]
@orangecoding Thank you very much!
