### ISSUE TITLE
[Immoscout] ScrapingAnt got blocked

### ISSUE THREAD

**Issue by DorelComan** [orangecoding/fredy#110]
Hi all,
thank you for your great project. Used it a few times in the past without issues.

I came back to use it now and I don't seem to be able to make it work. The setup is the same that worked a few months back. I rebased on latest master and built it. I get the following "blocked" warning and it doesn't seem to ever manage to get a response. 
Did anyone else notice this happening lately?
Could it be something with my free subscription? Before I used the paid one to get more tokens and then I cancelled it.

PS: I added a 100k token to it, cause I thought may have been a problem of suscription but it still doesn't work

Started Fredy successfully. Ui can be accessed via http://localhost:9998
Started API service on port 9998
ScrapingAnt got blocked. Retrying 1 / 10
ScrapingAnt got blocked. Retrying 2 / 10

**Comment by orangecoding** [comment]
Immoscout keeps adding more and more bot protection (which makes sense for them) it is a cats and mice game.
I will get in contact with scraping ant, but for now I strongly recommend to use the other provider, as almost everybody adds their listings to many provider, not just immoscout.

I'll get back to you
