### ISSUE TITLE
web UI refreshes to empty page or 404

### ISSUE THREAD

**Issue by Rowanion** [orangecoding/fredy#114]
Wanted to tweak something in the UI after a log time running unattended.
After login the jobs pages flashes briefly and I just get an empty page.
A reload flashes the jobs page again and the empty page again.
Tried on current Chrome and Edge. All extensions disabled.
I am on commit 4ed92b246f9c159c24d458e9d0db42c5acd52bd7, Running fredy on a Raspberry Pie4 on a latest bookworm.

Tried to use the latest version of fredy, with updating node and nvm and yarn and stuff.
There, I only get a 404 when accessing the UI page.

No clue what went wrong where. As the original system with old commit was running just fine a couple of months ago.

Any help appreciated!
Cheers!

**Comment by orangecoding** [comment]
I assume there are some js errors. @Rowanion please open the dev console and check if there are ANY issues in the console. If so, post em here plz

**Comment by Rowanion** [comment]
![js-errors](https://github.com/user-attachments/assets/43634e53-997d-4cd7-bdd5-8c5b7a373b30)

**Comment by orangecoding** [comment]
I was trying to fix it, but no matter what I try, I don't get this error. Seems to me your configuration is broken. Can you click on the right side where it says index-xxx.js:76 and screenshot where the error actually appears?

**Comment by Rowanion** [comment]
![image](https://github.com/user-attachments/assets/a9bb4f98-f2cc-4d4a-8050-cc59f3247788)

Sure. Here it is.

But maybe It's better if I tell you how I run it.
As the average max time a flat offer is online at immoscout24 is just under 5 minutes, I wanted to make use of multiple free ScrapingAnt accounts for the same query.
So, I duplicated the whole fredy folder and just changed the ScrapingAnt credentials and the port number in the settings. 
Then I start each other instance after a certain amount of minutes - so that each ScrapingAnt account will have enough tokens for a month and no query is run double.
This seem to cause this. I have an instance with all the unrestricted providers - I can log in just fine.
I have another single instance for immonet - where I can login just fine. But all the immoscout instances are giving me this error.
Might this be related to the jobID being the same? Or something like that?

**Comment by orangecoding** [comment]
Mhm, so to recap:
- you do have 2 instances of Fredy running
- they don't really know each other as they have different port numbers
- you made sure they are having their own directory for database files...?
- you run them on different times

Did I get this correctly?
IF yes, please provide also answers to:
- How do you make sure they are started on different time intervals? Do you just start one and then wait a couple of mins and then start the other?
- Does this error occur on both instances?
- Can you check on the chrome-dev console on the network tab is something's fishy's coming in?
- I don't think I'll be able to fix this without the config and the db files. IF you want to provide it, make sure to remove sensible data like the api key.

**Comment by orangecoding** [comment]
>It's more like 12 instances.
the f.. Wouldn't it be cheaper (and more fair) to just support scrapingant by purchasing some credits?

I think I need the db folder for this ;)

**Comment by orangecoding** [comment]
@Rowanion I'm still waiting on the necessary data.

**Comment by crepererum** [comment]
FWIW I can also reproduce this issue:


`conf/config.json`:

```json
{"interval":10,"port":9998,"scrapingAnt":{"apiKey":"1223","proxy":"datacenter"},"workingHours":{"from":"17:00","to":"18:00"}}
```

`db/jobListingData.json`:

```json
{
  "LzY5uiTH_hXWVK1vRB3Z7": {
    "lastExecution": 1731765539518
  }
}
```

`db/jobs.json`:

```json
{
  "jobs": [
    {
      "id": "LzY5uiTH_hXWVK1vRB3Z7",
      "userId": "bw9WqhLhe-IHCvfTWooVR",
      "enabled": true,
      "name": "test",
      "blacklist": [],
      "provider": [
        {
          "name": "Immoscout",
          "id": "immoscout",
          "url": "https://www.immobilienscout24.de/Suche/de/hamburg/hamburg/hamburg-nord/barmbek-sued/wohnung-mieten?numberofrooms=3.0-&price=-1400.0&livingspace=60.0-&pricetype=rentpermonth&enteredFrom=result_list"
        }
      ],
      "notificationAdapter": [
        {
          "id": "console",
          "name": "Console",
          "fields": {}
        }
      ]
    }
  ]
}
```

`db/users.json`:

```json
{
  "user": [
    {
      "id": "bw9WqhLhe-IHCvfTWooVR",
      "username": "admin",
      "password": "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
      "isAdmin": true,
      "lastLogin": 1731765247713
    }
  ]
}
```

I've tried this with Firefox 132.0.1 and Chromium 131.0.6778.69.

Fredy was started with:

```console
docker run \
  --rm \
  -it \
  -p 9998:9998 \
  -v ./conf/:/conf \
  -v ./db/:/db \
  ghcr.io/orangecoding/fredy:master
```

**Comment by orangecoding** [comment]
@crepererum what version of Fredy do you use? Latest?

**Comment by crepererum** [comment]
yes, the exact image is `ghcr.io/orangecoding/fredy@sha256:052956dcc160b1f64a712c65ae401b21ec7ffc1099c2570d959d71ff59e757dc`

**Comment by orangecoding** [comment]
@crepererum thanks. with your configs, I was able to find an issue. IF the (scrapingant) api key is wrong, it does not return a parsable processingTime, thus the error. 
Can you please check in your setup and open the chrome dev console, go to the network tab and search for the xhr call `http://localhost:5173/api/jobs/processingTimes`? I'm interested in the response. If I use a wrong api key, it returns this:

```
{
    "interval": 10,
    "lastRun": null,
    "scrapingAntData": {
        "detail": "API token is wrong. Please visit https://app.scrapingant.com/profile to check your token settings"
    }
}
```

IF this is the same for you, my next question would be: Why do you use a wrong api-key :)

**Comment by orangecoding** [comment]
Wait a second, an initial version of the config should be available right from the very first start::

**Comment by orangecoding** [comment]
Yeah, I do agree ;)
A fix will come together with a bigger change with the next release.

**Comment by orangecoding** [comment]
@crepererum With the latest release of fredy, this should be fixed. Please check it out.
https://github.com/orangecoding/fredy/releases/tag/10.3.0

**Comment by crepererum** [comment]
works, thanks!
