### ISSUE TITLE
Docker build failed:  The command '/bin/sh -c npm run prod' returned a non-zero code: 2

### ISSUE THREAD

**Issue by MahatmaX** [orangecoding/fredy#17]
Hi,
I was trying to build fredy using 'docker-compose up' and the build failed in "Step 12/15 : RUN npm run prod".

Log output attached (only for step 12, all previous steps completed)

[fredybuild.log](https://github.com/orangecoding/fredy/files/6166820/fredybuild.log)

Docker version in use:

Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

**Comment by orangecoding** [comment]
@MahatmaX hi. I've pushed some fixes. It should work now. Please use `docker-compose` and tell me how it goes. Locally it works for me, sorry for the inconvenience.

**Comment by MahatmaX** [comment]
docker-compose now works. Fredy is up and running :-)

Thanks a lot!
