### ISSUE TITLE
Only one notification is sent with duplicated adapters

### ISSUE THREAD

**Issue by saschnet** [orangecoding/fredy#19]
I have the use case that I want to send two emails to two different recipients within a single job.

Therefore, I added a second Mailjet Notification Adapter within the same job with the second recipient address:
![grafik](https://user-images.githubusercontent.com/33368683/112762836-3648b100-9002-11eb-86e2-9019ce1d9461.png)

When new alerts show up, only a single notification within the same adapter type is sent and the other adapter ignored. Other adapters (here Console) are successfully triggered.

**Comment by orangecoding** [comment]
@saschnet This should now also be fixed, see https://github.com/orangecoding/fredy/commit/9726079f62deab6cd8cf91c70927721a70e3007c

By the way, Fredy is open source, I'd appreciate a pr with a potential fix if possible ;)

Thanks and sorry for the inconvenience.

**Comment by saschnet** [comment]
Thank yo for the super quick fix.

I definitely have in mind providing a PR next time. As I haven't worked with Nodejs so far, I thought making aware of a bug is better than nothing for the start.

**Comment by orangecoding** [comment]
@saschnet I absolutely appreciate you to create this bug, don't get me wrong. This is what open source is about. Be nice to each other, help and get help :)
