### ISSUE TITLE
Make the user aware of ongoing processes or waiting times

### ISSUE THREAD

**Issue by carstenhag** [orangecoding/fredy#22]
I've set up Fredy now in an Immoscout + Telegram combo, but I do not know what it is doing. Is it waiting for the next scan, did it already scan something, or did something go wrong in the Telegram setup?

Would be good to have some indicators for these things :)

![firefox_2hj49GRmEK](https://user-images.githubusercontent.com/3776997/118107131-ad81ab00-b3de-11eb-9b7a-4a5f7a1fa352.png)

**Comment by orangecoding** [comment]
What exactly would you expect here? Something like "next run at..."?

**Comment by carstenhag** [comment]
Yes, last run and next run would be nice. Currently the interval is also not shown in the Frontend, with last/next run this is basically shown as well.

**Comment by orangecoding** [comment]
![image](https://user-images.githubusercontent.com/1519704/118169594-68cf3180-b429-11eb-8a2f-bbda69f4f8c2.png)

fixed.

**Comment by carstenhag** [comment]
Yay, looks nice!
