### ISSUE TITLE
Allow editing provider and notification adapter settings

### ISSUE THREAD

**Issue by carstenhag** [orangecoding/fredy#23]
Currently one can only create a providers/adapter and delete it, but it's not possible to edit them.

**Comment by orangecoding** [comment]
For notification adapter, it kinda makes sense as you have to type in the api keys etc, but for providers, I'm not so sure it makes sense. 

In the end, you would go back to the page (immoscout for instance) copy the url and replace the current one. Removing the old provider and re-adding it is somehow the same effort  no?

**Comment by carstenhag** [comment]
Sort of the same thing, but in my brain it goes like this: I want to edit the provider/the URL, deleting it and adding a new one feels weird.  
So basically it's just an UX thing. You can leave it as is if you want to :)

**Comment by orangecoding** [comment]
@carstenhag notification adapter are now editable.

**Comment by carstenhag** [comment]
Yay, thanks!
