### ISSUE TITLE
Immoscout: Parse listing from basesearch given html source & dump search results

### ISSUE THREAD

**Issue by jaspb** [orangecoding/fredy#30]
Given the results of a base search, I would like to parse the immoscout html source for a given listing in order to filter by attributes that are not exposed by the immoscout search functionality.

For instance, fields like "Bezugsfrei ab" or "Ausstattung" are relevant cues as to whether a user might be interested in a search result or not. Is this feature available in Fredy or how could it be added (to Fredy or in an offline parser)?

**Comment by jaspb** [comment]
As an extension of this use case, is it possible to dump all search results given a base search? 

From what I can see, Fredy runs a diff against the search results that are available at time T vs T+1 and only publishes the delta, ie. new listings to a provider. This seems to assume that a user is familiar with all search results at time T.

**Comment by orangecoding** [comment]
Hi @jaspb , 

sorry im on vacation, thus it took a while to respond. While I can see why this could be helpful, I don't see this as a case that would be helpful for the vast majority of Fredy users, thus I would not add it into Fredy. 

I'd suggest you fork Fredy and implement something like this yourself, it should be pretty straight forward. If you need any help, you can ping me for sure :)
