### ISSUE TITLE
Telegram "      description: 'Bad Request: message is too long'"

### ISSUE THREAD

**Issue by coxtor** [orangecoding/fredy#35]
Hi, awesome App! However, it would be greate to have smtp notification provider and I receive this error some times using telegram: 
    data: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: message is too long'
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]

perhaps split too long messages in multiple messages ?

**Comment by orangecoding** [comment]
Thanks for the report! About the smtp, this is not too easy unfortunately, that's why I've decided to go with services like SendGrid. As for the error, I will check it.

**Comment by orangecoding** [comment]
@coxtor fixed with https://github.com/orangecoding/fredy/commit/8361d9c8ff5f33b87f50bd2d5c74d3250eb422fc
