### ISSUE TITLE
Windows does not understand "export"

### ISSUE THREAD

**Issue by sven-simonsen** [orangecoding/fredy#51]
**Describe the bug**
When running `yarn run prod` on a windows machine the command `export BUILD_DEV='false'` in package.json fails with `'export' is not recognized as an internal or external command`.

**Expected behavior**
Replacing all instances of `export` with `set` if running on a windows machine fixes the issue. I don't know how to do that in a dynamic way though.

**Comment by orangecoding** [comment]
I was planning on using this: https://www.npmjs.com/package/run-script-os

Would you mind checking it and send a pr if it works coz I don't have any windows os.

**Comment by sven-simonsen** [comment]
Added a PR from a fork. Dunno if that was the correct way to do it, if not just copy the change to a better structured branch.
