### ISSUE TITLE
Error message on console

### ISSUE THREAD

**Issue by basarozcan** [orangecoding/fredy#53]
Steps to produce
* Created an Immoscout provider  with an valid url
* creating telegram adapter (testing message received)

On every request, I see an error like that:
`Error while trying to scrape data. Received error: Request failed with status code 423`

**Comment by orangecoding** [comment]
@basarozcan Hi,
which version of Fredy are you using? StatusCode 423 actually means that the request got blocked which should be kinda fixed when using ScrapingAnt's residental proxies
