### ISSUE TITLE
Residential and datacenter strategy for Immobilienscout24 scraping

### ISSUE THREAD

**Issue by kami4ka** [orangecoding/fredy#56]
**Is your feature request related to a problem? Please describe.**
Datacenter scraping for Immobilienscout24 is successful too but may require more retries and a bit slower, while residential is faster and more expensive.

**Describe the solution you'd like**
Allow 2 strategies for Immobilienscout24 scraping:
1) Datacenter-only - retry N times with datacenter proxies (**note**: also retry when the status code is 404, it's a known behavior for this specific proxy pool)
2) Residential-included - try with datacenter (better with retries) and then switch to residential

So it would be possible to decide whether use residential or not, but the retry would always apply.

**Additional context**
Datacenter-only approach would always return a successful result, but it might take some time, while the residential-included approach would be faster and more expensive. It's a result of ScrapingAnt's custom proxy pool feature applied for Fredy.

**Comment by denisalevi** [comment]
I think this would make a lot of sense. Using residential proxies cost 250 credits per call, while datacenter proxies cost only 10 with ScrapingAnt. That gives you just above **1 call** per day in the free plan and even with the 10k credit plan you end up with less than 14 calls per day. That makes using residential proxies unfeasible IMHO. I ended up downgrading to version 5.5.0 and implementing retries, which works fine.

**Comment by kami4ka** [comment]
@denisalevi could you, please, create a PR to this repo?

**Comment by denisalevi** [comment]
Hi @kami4ka, I'm not a js developer and its just some hacky lines added to an older version of the repo. I'll try to clean it up or make it somehow available soon!

But from a quick look at the current repo version, it looks like it is all there in [requestDriver.js](https://github.com/orangecoding/fredy/blob/676d48807a71994b8350d45a1a4779f1fa27dbf3/lib/services/requestDriver.js). From a quick look I didn't get the logic entirely though. Could it be that something is missing there? An option to set `MAX_RETRIES_SCRAPING_ANT` and not try residential proxies should be possible?
@orangecoding Any thoughts? :)

**Comment by orangecoding** [comment]
I'm going to give it a shot in a couple of days, currently I have some private responsibilities I have to deal with. Once this is sorted, I'm coming back to this :)

**Comment by orangecoding** [comment]
@kami4ka If I understand you correctly, you suggest to make the use of residental proxies an option and let the user decide whether they want to have a faster and more stable solution or whether they want to have a cheaper one?

I do like this approach tbh

**Comment by kami4ka** [comment]
@orangecoding Yup. Exactly. So retry mechanism would remain the same, only the proxy type is changeable

**Comment by denisalevi** [comment]
I would maybe add an option to set the number of retries when using residential proxies? I think with 3 retries (current setting?) it fails quite often. I have 8 retries and I think it always succeeds with those. I can check the logs again next week, its running on a Pi that I don't have access to right now.

**Comment by orangecoding** [comment]
@kami4ka what was again the comment about retries.. I remeber you once told me that if the return value is != 200 meaning if no success, the customer is not charged. Is this still true? If this is true, I don't know if it makes sense to make the number of retries configurable, but rather setting it to let's say 10. Of course only if this doesn't cost 250 credits per retry ;)

**Comment by orangecoding** [comment]
I have just added an option to configure the proxies (still to be finished) and once again noticed... I am no designer at all.. 👯 
<img width="897" alt="image" src="https://user-images.githubusercontent.com/1519704/173136104-d8c456ee-84bf-440f-8e85-9248b1aeabc6.png">

**Comment by kami4ka** [comment]
> @kami4ka what was again the comment about retries.. I remeber you once told me that if the return value is != 200 meaning if no success, the customer is not charged. Is this still true? If this is true, I don't know if it makes sense to make the number of retries configurable, but rather setting it to let's say 10. Of course only if this doesn't cost 250 credits per retry ;)

Yup. That's true.
Every non-200 response from ScrapingAnt is not billable.

**Comment by kami4ka** [comment]
> I have just added an option to configure the proxies (still to be finished) and once again noticed... I am no designer at all.. 👯 <img alt="image" width="897" src="https://user-images.githubusercontent.com/1519704/173136104-d8c456ee-84bf-440f-8e85-9248b1aeabc6.png">

10.000 free API credits :-)

**Comment by orangecoding** [comment]
Ahh right. Thanks.

**Comment by feliche93** [comment]
@orangecoding thanks for creating this! I am also thinking about how to solve the immoscout captcha.

An idea was to use postman to intercept the app traffic from my iPhone, to rereplicate the search query and get data clean. This works great so far with the following request (unauthenticated user in-app):

```
import requests

url = "https://api.mobile.immobilienscout24.de/search?exclusioncriteria=swapflat&equipment=balcony&features=adKeysAndStringValues,virtualTour,contactDetails,viareporting,nextgen,calculatedTotalRent,listingsInListFirstSummary,grouping,projectsInAllRealestateTypes&pagesize=20&priceType=calculatedtotalrent&geocodes=/de/berlin/berlin&price=700-1400&sorting=-firstactivation&haspromotion=false&realestatetype=apartmentrent&numberofrooms=2-3&channel=is24&searchType=region&pagenumber=1&publishedafter=2022-06-11T21:30:24"

payload={}
headers = {
  'host': 'api.mobile.immobilienscout24.de',
  'authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InByb18yMDIxLTEyLTE1VDEzOjQ2OjI0LjAyMTgzMVoifQ.eyJzY29wZSI6WyJST0xFX1VTRVIiLCJTXzNMT0FVVEhfQVVUT19DT05GSVJNQVRJT04iLCJTX0FDQ0VTU19NT0RJU19BUElfUFJJQ0VfSElTVE9SWSIsIlNfRVhQT1NFIiwiU19HSVNfR0VPQ09ERSIsIlNfR0lTX0dFT0hJRVJBUkNIWSIsIlNfR0lTX0dFT19BVVRPQ09NUExFVEUiLCJTX0dJU19SRVZFUlNFX0dFT0NPREUiLCJTX0tBVUZQTEFORVIiLCJTX0xPR0lOX0FTX1VTRVIiLCJTX1JFQUxfRVNUQVRFX1JFQUQiLCJTX1JFQUxfRVNUQVRFX1dSSVRFIiwiU19SRVBPUlRJTkdfRU5BQkxFRCIsIlNfUkVUUklFVkVfQ09OVEFDVF9ERVRBSUxTX1BIT05FIiwiU19SRVRSSUVWRV9VTlBVQkxJU0hFRF9FWFBPU0UiLCJTX1NFQVJDSF9JUzI0IiwiU19TRUFSQ0hfVU5MSU1JVEVEX1BBR0VfU0laRSIsIlZBTFVBVElPTl9QREZfUkVBRCIsIlZBTFVBVElPTl9QREZfV1JJVEUiLCJjb25zdW1lckVudGl0bGVtZW50Lm15LnJlYWQiLCJjb252ZXJzYXRpb24udXNlci5hbGwiLCJtb2JpbGUucHJvZHVjdC5hcGkiLCJtb2JpbGUuc29sdmVuY3kucmVhZCIsIm1vYmlsZS5zb2x2ZW5jeS53cml0ZSIsIm9jYS5vZmZlcnMucmVhZCIsIm9jYS5wcmljZXJhbmdlLnJlYWQiLCJwcmljZWhpc3RvcnkucmVhZCIsInByb2ZpbGUuYXBpLnJlYWQiLCJwcm9maWxlLmFwaS53cml0ZSIsInByb2plY3RleHBvc2UubWFwaS5tYWlsIiwicHJvamVjdGV4cG9zZS5tYXBpLnJlYWQiLCJwcm9qZWN0ZXhwb3NlLm1hcGkucmVwb3J0IiwicHJvc3BlY3Rvci5hcGkiLCJyZWNvbW1lbmRlZC5leHBvc2VzLmFwaSIsInJlbG9jYXRpb25yZXF1ZXN0Iiwic29sdmVuY3kuYXBpIiwic3Vic2NyaXB0aW9uLmFwaS5yZWFkIiwic3Vic2NyaXB0aW9uLmFwaS53cml0ZSIsInN1cnZleS5hcGkucmVhZCIsInN1cnZleS5hcGkud3JpdGUiXSwia2lkIjoicHJvXzIwMjEtMTItMTVUMTM6NDY6MjQuMDIxODMxWiIsImV4cCI6MTY1NDk3OTcwMCwianRpIjoieUdyU3pHVTU3aDJWbzhHVFBKOGtTOEtlR2lzIiwiY2xpZW50X2lkIjoiSW1tb2JpbGllblNjb3V0MjQtaVBob25lLVdvaG5lbi1BcHBLZXkifQ.Qn8AxNvx5NyWEcXa0JENa7RazW7gZkhXLfXW9siLsvFYKsaKcu24X22ZZ7Ku2-rNuZ4aoBVmPiPrR75UNdlLqxEbfBUkMVY3-9oetbRDXIlVMqLVx25KPmgSbX8vAj0e1RYB9zlnvHK0465-soO7xooeOi8RoYeW6nCeiFrupaXSQcwOYNHvuToO6Xvthf9CPFdS_jkfkX7cJn1FriHYgJ3gPTDPVV8zVqrkNSDqPFj5nyWaNHHhr374CkX3fZHz-tzRUmCR9xC87Clu-a13nfGzhsqZHmxcpjfR6TT7Y-tv6fEyxBASbTADZXKqLNCy8pUGE1dUi1TsE4bFWMv11w',
  'x_is24_client_id': '0D24B913AE4D4A8F94BA904FD707A54D',
  'x-is24-device': 'iphone',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'de-de',
  'x-emb-st': '1654976150117',
  'accept': 'application/json',
  'user-agent': 'ImmoScout_23.19_15.5_._',
  'connection': 'keep-alive',
  'x-emb-id': 'C48F68553B63477D8AE1721B274975D3',
  'cookie': 'utag_main=v_id:018135d997930022e9c4daa68c4c0006f009e067004c3$_sn:7$_se:1$_ss:1$_st:1654906318172$utm_source_30d:ios%3Bexp-1657496521818$psn_usr_login_cookie:false%3Bexp-1686001862773$cdp_ab_splittest:GroupB$ses_id:1654904518172%3Bexp-session$_pn:1%3Bexp-session$referrer_to_lp:%3Bexp-session$utm_campaign_ses:ppa_messenger_entrance%3Bexp-session$utm_medium_ses:app%3Bexp-session$utm_source_ses:ios%3Bexp-session$survey_overlay:b%3Bexp-session; longUnreliableState="dWlkcg==:YS0wMTgxMzVkOTk3OTMwMDIyZTljNGRhYTY4YzRjMDAwNmYwMDllMDY3MDA0YzM="',
  'x-postman-captr': '637116'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text) 
```

An issue is that the JSON web token expires at some point, so it needs to be recreated, to be able to continue monitoring. Did anyone already go down this path and concluded that it's pointless to continue figuring ou how the JWT gets signed?

**Comment by orangecoding** [comment]
@denisalevi @kami4ka I have added all necessary changes, would you mind taking a look and do a quick review?
https://github.com/orangecoding/fredy/pull/59/files

It's pretty straight forward:
- The user now has an option to chose between datacenter & residential proxies
- The retry mechanism now doesnt fail on 404 as @kami4ka suggested
- The retry is now far simpler, as it only checks for the proxy setting, stored by the user
- There are now up to 10 retries

**Comment by denisalevi** [comment]
Great, thanks a lot! I'll try it out tonight :)
