### ISSUE TITLE
Make fredy runnable on raspberry pi

### ISSUE THREAD

**Issue by HJoentgen** [orangecoding/fredy#67]
Hey,

over the weekend I tried to set up a Docker on my Raspberry Pi 3 with Fredy running.
The image building fails at `RUN yarn install `with an non-zero code: 133, even though a manual `yarn install` yields no errors.
When trying to use the available image, it fails, too, because the Raspberry Pi is using a different hardware architecture.

Has anybody else tried to run in on a Pi and could share some insights?

**Comment by orangecoding** [comment]
Mhm, I tried it on my pi 4 and it runs without any problems. (I don't have a pi 3). Anybody here that has a pi 3 that can check this issue?

@HJoentgen Have you tried the docker setup on your regular computer just to verify it works correctly?

**Comment by HJoentgen** [comment]
@orangecoding If it works on your Pi 4, then it should work on my Pi 3.
Did you build the image yourself on the Pi or did you use the the existing image? 
`docker pull ghcr.io/orangecoding/fredy:master`

**Comment by orangecoding** [comment]
I used the existing image

**Comment by orangecoding** [comment]
Does it work for you on a normal pc/mac?

**Comment by orangecoding** [comment]
I'll close this issue as I haven't heard anything back from you.
