### ISSUE TITLE
Possible to exclude estate agents?

### ISSUE THREAD

**Issue by mygrexit** [orangecoding/fredy#68]
Hello Guys,
first of all: Love your project, thank you!!!

I'd like to find listings without real estate agents or at least exclude SOME of them. We have 3 or 4 pretty evil ones in our city that I would never buy/rent from. It doesn't seem like the blacklist excludes them (only tried immowelt) would it be possible to add that as a feature?

Looking forward to your reply!

**Comment by orangecoding** [comment]
Hi. 
How would you identify a listing from this agent?

**Comment by orangecoding** [comment]
@mygrexit I'd need some more input plz, otherwise I'll close this issue.
