### ISSUE TITLE
"Unexpected end of file" when trying to scrape Immowelt

### ISSUE THREAD

**Issue by ULTRA-VAGUE** [orangecoding/fredy#69]
Whenever I try to setup Immowelt I get this error code.

`"Error while trying to scrape data. Received error: unexpected end of file"`

It doesn´t scrape anything off of Immowelt, even with a new Config and Database .json file.
I´ve checked the formatting and there doesn´t seem to be any issues there. 

How can I resolve this?

This is the specific String I used with fredy:
https://www.immowelt.de/liste/berlin/wohnungen/mieten?ami=30&d=true&pma=700&sd=DESC&sf=TIMESTAMP&sp=1

**Comment by orangecoding** [comment]
Thanks for the report. I'll check.

**Comment by orangecoding** [comment]
Mhm. it works totally fine for me. Can you do me a favour, go into 
```
/test/provider/testProvider.json
```
and add your url  in here:
```
 "immowelt": {
    "url": "https://www.immowelt.de/liste/berlin/wohnungen/mieten?ami=30&d=true&pma=700&sd=DESC&sf=TIMESTAMP&sp=1",
    "enabled": true
  },
```

then run `yarn run test`. All Tests are passing for me.

**Comment by ULTRA-VAGUE** [comment]
all tests are also passing for me, however the issue still persists.

**Comment by ULTRA-VAGUE** [comment]
to add to that: 
I have created seperate jobs for every provider, when I disable immowelt everything starts working normally again.

**Comment by orangecoding** [comment]
If the test works, everything else should work as well,as the test is only using the stuff that is also being used while doing 'real' work.
I'll check further

**Comment by orangecoding** [comment]
Hi @ULTRA-VAGUE Can you pull the latest master, run 
`npm install` or `yarn` (or whatever you use) and try again?
See https://github.com/orangecoding/fredy/commit/7d0ec72a0c3b6aaf8ef77866aa12864584288c53
