### ISSUE TITLE
Add landlord/owner/offerer and address option

### ISSUE THREAD

**Issue by vomJupiter** [orangecoding/fredy#71]
I'd love to have the opportunity to scrape landlords and the related addresses (when given) for mapping purposes. I'm particularly interested in housing groups and less concerned with private names or the like.

The tool I am looking for is for (journalistic) research purposes. It would be great if you could add such a feature.

The only alternative I can see is to search it by hand, which would be much more time-consuming.

**Comment by orangecoding** [comment]
Hi
sorry, fredy is not a tool to scrape this kind of information, nor is it a tool to collect personal information.

**Comment by vomJupiter** [comment]
Hi,
again: I was talking about groups and companies with a substantial power on the housing market. One could easily argue wether this is personal information or not. Nonetheless, thanks for your reply!
