### ISSUE TITLE
Ebay kleinanzeigen links not recognized

### ISSUE THREAD

**Issue by Bloxxxi** [orangecoding/fredy#78]
EBay kleinanzeigen links stopped working for me although it worked a week ago.
Example link: https://www.kleinanzeigen.de/s-wohnung-mieten/muenchen/preis::1200/c203l6411r30
Output: The URL you have copied is not valid.

Furthermore, ebay kleinanzeigen will update its website soon in May. The current links may be broken because it's their transition towards the new website.

**Comment by Bloxxxi** [comment]
The links are broken because www.ebay-kleinanzeigen.de got changed to www.kleinanzeigen.de in the URL.

**Comment by orangecoding** [comment]
Currently I'm not available, but I will fix it soon-ish
Thanks

**Comment by orangecoding** [comment]
See https://github.com/orangecoding/fredy/releases/tag/7.2.1
