### ISSUE TITLE
SendGrid leads to: "TypeError: Cannot read properties of undefined (reading 'fields')"

### ISSUE THREAD

**Issue by aeneasr** [orangecoding/fredy#80]
**Describe the bug**

Configuring SendGrid leads to a Type Error

**To Reproduce**

1. Configure SendGrid as a notification adapter
2. Fill out details
3. Click "try notification adapter"

**Expected behavior**

Should work

**Screenshots**

<img width="1234" alt="Bildschirmfoto 2023-09-19 um 12 25 20" src="https://github.com/orangecoding/fredy/assets/3372410/3651086e-3228-494b-8008-7b7330987f9e">

**Additional Context**

Getting this issue both with 7.3.2 and fbad4456d75eec7a3d158adea6ecd98e4ec176ae

**Comment by orangecoding** [comment]
Thx for the report, I will check it and get back to you.

**Comment by orangecoding** [comment]
@aeneasr fixed here. https://github.com/orangecoding/fredy/commit/17b4bad2e4299326b2910f12eeb3cb1ab2eaa81b

**Comment by aeneasr** [comment]
🙏
