### ISSUE TITLE
Error when clicking on general settings

### ISSUE THREAD

**Issue by alice17** [orangecoding/fredy#83]
Hello, I'm using Fredy for the first time. I noticed that when I click on general settings on the front end nothing shows and I get this error on the front page:

`Uncaught Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

**Comment by orangecoding** [comment]
Hi.
Sorry for the inconvenience. I'm currently on vacation. I'll look into this when I'm back.

**Comment by orangecoding** [comment]
Hi @alice17

no matter what I try, I don't get this error. Can you please give me some more information?
- What browser are you using?
- Are you using the latest Fredy version?
- Can you share your config.json (remove all passwords)

**Comment by alice17** [comment]
Hello, it has disappeared after re launching the container. However, I was using Firefox with last Fredy's version,
