### ISSUE TITLE
New Notification Adapter

### ISSUE THREAD

**Issue by strtob** [orangecoding/fredy#84]
Hi,

This is really an amazing! 

How can I code a new adatper? I've copied as template an existing one, but it seems that the provider are registered or listet anywhere which will put into the select input field.

Thanks a lot!

Best,
Tobi

**Comment by orangecoding** [comment]
@strtob hi Tobi.

Sorry I read your message several times but I couldn't make sense out of it. Could you try to explain again what your problem is?
