### ISSUE TITLE
Immoscout API

### ISSUE THREAD

**Issue by ManuelWittke** [orangecoding/fredy#98]
Hi pal,

Thank you for the great application! 

Have you allready considered using the immoscout API?
https://api.immobilienscout24.de/

Manu

**Comment by orangecoding** [comment]
Hi @ManuelWittke 
interesting.. no I haven't yet looked into this. Do you know if the usage of that api is free or does it come with a cost? I am pretty damn sure that they don't provide a free api which can be used to scrape their listings as this is something they sell for lot's of $$..

**Comment by dekiesel** [comment]
Not free, unfortunately:

https://api.immobilienscout24.de/terms-of-use/de/#3-preise

**Comment by orangecoding** [comment]
<img width="567" alt="image" src="https://github.com/user-attachments/assets/a4aa2b91-e487-43e0-9a6b-38a4f46a4f71">
ok lol. 60 eur is probably nothing any of Fredy's users is willing to pay. Thanks a ton for the input, but I'll close this for now ;)
